### ISSUE TITLE
Repo size growth exponential

### ISSUE THREAD

**Issue by chrisjsimpson** [geoacumen/geoacumen-country#4]
The full clone of this repo is currently ~ 300mb and growing, which can make cloning challenging on patchy networks. 

I suspect this is due to:

https://github.com/geoacumen/geoacumen-country/actions/runs/2288191004/workflow#L41

It can be overcome by setting the clone depth to 1
```
git clone --depth=1 https://github.com/geoacumen/geoacumen-country.git
```

If this needs/wants to be addressed at all I guess but could be wrong git lfs may be relevant here: https://git-lfs.github.com/

thanks for maintinaing this useful resource!

**Comment by ColdHeat** [comment]
Thanks for reporting this, I would not have noticed since I haven't cloned it in awhile. 

I suspect the issue is the ever changing `ip2asn-combined.tsv`. I think the best idea would be to not store that file and pruning it from history. The original idea was to see how IPs have changed over time but that's likely not a real usecase for anyone. 

If you can PR a change to remove `ip2asn-combined.tsv` from the repo and history completely I would accept it. 

EDIT: However I imagine that you can't PR it sincei t would require a force push to rewrite history. I will see what I can do when I have some more time.

**Comment by ColdHeat** [comment]
I've removed the previous copies of `ip2asn-combined.tsv` and `Geoacumen-Country.mmdb` and moved `Geoacumen-Country.mmdb` to git lfs. The repo should also no longer track the `ip2asn-combined.tsv` file.
